service: dofus-items-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  versionFunctions: false
  apiKeys:
    - dofus-items-api-register-key
  environment:
    REGION: ${self:provider.region}
    APPLICATION_PLATFORM_ARN: arn:aws:sns:eu-west-1:117476207589:app/GCM/Dofus-Items
    TOPIC_ARN: arn:aws:sns:eu-west-1:117476207589:dofus-items-daily-topic
    SUBSCRIPTION_TABLE: dofus-items_subscriptions
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "SNS:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "DynamoDB:*"
      Resource: "*"

functions:
  # Register
  register-device:
    name: dofus-items_register-device
    handler: register.handler
    memorySize: 128
    events:
      - http:
          path: /register
          method: post
  # Notify
  send-notification:
    name: dofus-items_send-notification
    handler: send.handler
    memorySize: 128
    events:
      - schedule:
          # rate: cron(0 9 * * * *)
          rate: cron(* * * * ? *) # TODO testing
          enabled: false
      - http:
          private: true
          path: /notify
          method: post

resources:
  Resources:
    devices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dofus-items_subscriptions
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
