service: dofus-items-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  versionFunctions: false
  apiKeys:
    - dofus-items-api-register-key
  environment:
    NOTIFICATION_TOPIC_FR: dofus-items-topic-fr
    NOTIFICATION_TOPIC_EN: dofus-items-topic-en

functions:
  # Register
  register-device:
    name: dofus-items_register-device
    handler: src/handler.register
    memorySize: 128
    events:
      - http:
          path: /register
          method: post
  # Notify
  send-notification:
    name: dofus-items_send-notification
    handler: src/handler.notify
    memorySize: 128
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
          enabled: true
      - http:
          private: true
          path: /notify
          method: post
